version: '1.0'
services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=krainet-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=user
    volumes:
      - database-data:/var/lib/krainet-db
    restart: always
  backend:
    build: .
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/krainet-db
      db-username: user
      db-password: root
    depends_on:
      - db
    restart: always
volumes:
  database-data: